# Generated by Django 5.2.6 on 2025-09-23 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
