# Generated by Django 5.2.6 on 2025-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_visita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='apellido',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
