# Generated by Django 5.2.6 on 2025-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_apellido_alter_visita_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='apellido',
            field=models.CharField(max_length=35),
        ),
    ]
