# Generated by Django 5.2.6 on 2025-10-30 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_alter_visita_apellido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], default='EN_CURSO', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
