# Generated by Django 5.2.6 on 2025-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_visita_estado_visita_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='apellido',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
